<a href="https://colab.research.google.com/github/yeyomuri/fundamentos_redes_neuronales_con_Python_y_Keras/blob/main/dimensiones_tensores_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

##Vector

In [10]:
x = np.array([42, 3, 5, 3, 6, 7])
print('El tamaño de arreglo es: ', x.shape)
print('El número de dimensiones es: ', x.ndim)

El tamaño de arreglo es:  (6,)
El número de dimensiones es:  1


##Matiz


In [11]:
x = np.array([[2,3], [4,3]])
print('El tamaño de arregle es: ', x.shape)
print('El número de simensiones es: ', x.ndim)

El tamaño de arregle es:  (2, 2)
El número de simensiones es:  2


##Tensor

In [12]:
x = np.array([[[2,3], [4,5]], [[2,3], [4,5]]])
print('El tamaño del arreglo es: ', x.shape)
print('El número de dimensiones es: ', x.ndim)

El tamaño del arreglo es:  (2, 2, 2)
El número de dimensiones es:  3


##Reshape

In [19]:
x = np.array([[0,1], 
          [0,1], 
          [4,5], 
          [5, 7], 
          [8, 9]]
          )
print('El tamaño del arregl es: ', x.shape)
print('El número de dimensiones es', x.ndim)

El tamaño del arregl es:  (5, 2)
El número de dimensiones es 2


In [20]:
x.reshape(10,1)

array([[0],
       [1],
       [0],
       [1],
       [4],
       [5],
       [5],
       [7],
       [8],
       [9]])

In [21]:
x.reshape(2, 5)

array([[0, 1, 0, 1, 4],
       [5, 5, 7, 8, 9]])

##Transpuesta

In [23]:
x.T

array([[0, 0, 4, 5, 8],
       [1, 1, 5, 7, 9]])